routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::post('/product/{id}', 'ShopController@addToCart');
Route::resource('product', 'ShopController');
Route::resource('order', 'OrderController');
Route::get('/cart', 'CartController@show');
Route::get('/orders', 'OrderController@index')->name('orders');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    //
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user', 'paid', 'status',
    ];

    public function products() {
        return $this->belongsToMany('App\Product', 'order_products', 'order_id', 'product_id')
            ->using('App\OrderProducts');
    }

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function getTotal() {
        $total = 0;
        foreach($this->products as $product) {
            $total += $product->price;
        }
        return $total;
    }

}

app/OrderProducts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class OrderProducts extends Pivot
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'order_id', 'product_id'
    ];

    protected $table = 'order_products';
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'price', 'delivery'
    ];
    /**
     * The attributes that are guarded from changes.
     *
     * @var array
     */
    protected $guarded = [
        'id'
    ];

    public function orders() {
        return $this->belongsToMany('App\Order', 'order_products', 'product_id', 'order_id')
            ->using('App\OrderProducts');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    public function show()
    {
        $cart = Cart::all()->sortBy('name');
        return view('cart.show', compact('cart'));
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index() {
        $orders = Order::all();
        return view('orders.index', compact('orders'));
}

    /**
     * Display a product's page
     *
     * @param $id
     */
    public function show($id)
    {

        $order = Order::where('id', '=', $id)->get()->first();
        if (!$order) {
            abort(404);
        }
        return view('orders.single', compact('order'));
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

class ShopController extends Controller
{
    /**
     * Shop index, display all products
     */
    public function index()
    {
        $products = Product::all()->sortBy('name');
        return view('products.index', compact('products'));

    }

    /**
     * Display a product's page
     *
     * @param $id
     */
    public function show($id)
    {

        $product = Product::where('id', '=', $id)->get()->first();
        if (!$product) {
            abort(404);
        }
        return view('products.single', compact('product'));
    }

    /**
     * Add a product to the cart
     *
     * @param $id
     */
    public function addToCart($id)
    {
        $product = Product::findOrFail($id);
        if (!Session::get('cart'))
            Session::put('cart', []);
        Session::push('cart', $id);
        return back()->with('success', $product->name . ' added to cart');
    }

    /**
     * Clear the cart
     *
     * @param $id
     */
    public function emptyCart()
    {
        Session::forget('cart');
        return back()->with('success', 'Cart Emptied');
    }

    /**
     * Check out
     */
    public function checkout()
    {

    }


}

resources/views/cart/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                Winkelwagen
            </h1>
        </div>
    </div>

    <div class="columns has-margin-top-50 is-centered">
      <div class="columns">
        <div class="column is-one-third">

                      Product {{-- {{ $product->name }}--}}

        </div>
        <div class="column is-one-third">
                        Prijs: &euro; {{--{{ $product->price }}--}}
        </div>
        <div class="column is-one-third">
                    <a href="{{ url('/') }}" class="button is-danger">Verwijder</a>
        </div>
      </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title">
                HandigJoh!
            </h1>
            <h2 class="subtitle">

            </h2>
        </div>
    </div>
</section>
    @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }} {{ app()->version() }}</title>

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ asset('bulma-helpers.css') }}">

    </head>
    <body>
        <div id="app">
            <nav class="navbar has-shadow">
                <div class="container">
                    <div class="navbar-brand">
                        <a href="{{ url('/') }}" class="navbar-item">{{ config('app.name', 'Laravel') }}</a>

                        <div class="navbar-burger burger" data-target="navMenu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div class="navbar-menu" id="navMenu">
                        <div class="navbar-start"></div>

                        <div class="navbar-end">
                            <a class="navbar-item" href="{{ url('/orders') }}">Bestellingen</a>
                            <a class="navbar-item" href="{{ url('/product/') }}">Producten</a>
                            <a class="navbar-item" href="{{ url('/cart') }}">Winkelwagen</a>
                            @if (Auth::guest())
                                <a class="navbar-item " href="{{ route('login') }}">Login</a>
                                <a class="navbar-item " href="{{ route('register') }}">Register</a>
                            @else
                                <div class="navbar-item has-dropdown is-hoverable">
                                    <a class="navbar-link" href="#">{{ Auth::user()->name }}</a>

                                    <div class="navbar-dropdown">
                                        <a class="navbar-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                              style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </nav>
            @yield('content')
        </div>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                Bestellingen
            </h1>
        </div>
    </div>

    <div class="columns has-margin-top-50">
        @forelse($orders as $order)
            @if($loop->index >= 2 && $loop->index % 3 == 0)</div><div class="columns">@endif
        <div class="column is-one-third">
            <div class="card">
                <header class="card-header">
                    <p class="card-header-title">
                        Bestelling #{{ $order->id }}
                    </p>
                </header>
                <div class="card-content">
                    <div class="content">
                        @if($order->getTotal() >= 200)
                            Verzendkosten: &euro;0,00<br/>
                            Totaal: &euro; {{ $order->getTotal() }}
                        @else
                            Verzendkosten: &euro;12,50<br/>
                            Totaal: &euro; {{ $order->getTotal() + 12.50 }}

                        @endif
                    </div>
                </div>
                <div class="card-content">
                    <div class="content">
                        Status: {{ $order->status }}
                    </div>
                </div>
                <footer class="card-footer">
                    <a href="{{ route('order.show', $order->id) }}" class="card-footer-item button is-info">Lees
                        meer</a>
                </footer>
            </div>
        </div>
        @empty
            <div class="column">
                <h3 style="text-align: center;" class="title">Geen Bestellingen gevonden</h3>
            </div>
        @endforelse
    </div>
@endsection

resources/views/orders/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                Bestelling #{{ $order->id }}
            </h1>
        </div>
    </div>
    <div class="columns has-margin-top-50 is-centered">
        <div class="columns">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            Klant: {{ $order->user->email }} <br/>
                            @if($order->getTotal() >= 200)
                                Verzendkosten: &euro;0,00<br/>
                                Totaal: &euro; {{ $order->getTotal() }}
                            @else
                                Verzendkosten: &euro;12,50<br/>
                                Totaal: &euro; {{ $order->getTotal() + 12.50 }}

                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                Producten
            </h1>
        </div>
    </div>
    <div class="columns has-margin-top-50 is-centered">
        <div class="columns">
            @forelse($order->products as $product)
                <div class="column">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                  {{ $product->name }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                Prijs: &euro; {{ $product->price }}
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            @endforelse

        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                Winkel
            </h1>
        </div>
    </div>
    <div class="columns is-center">
        <div class="column is-one-third">
            Filter:

        </div>
    </div>

    <div class="columns has-margin-top-50">
        @forelse($products as $product)
            @if($loop->index >= 2 && $loop->index % 3 == 0)</div><div class="columns">@endif
        <div class="column is-one-third">
            <div class="card">
                <header class="card-header">
                    <p class="card-header-title">
                        {{ $product->name }}
                    </p>
                </header>
                <div class="card-content">
                    <div class="content">
                        Prijs: &euro; {{ $product->price }}
                    </div>
                </div>
                <footer class="card-footer">
                    <a href="{{ route('product.show', $product->id) }}" class="card-footer-item button is-info">Lees
                        meer</a>
                </footer>
            </div>
        </div>
        @empty
            <div class="column">
                <h3 style="text-align: center;" class="title">Geen producten gevonden</h3>
            </div>
        @endforelse
    </div>
@endsection

resources/views/products/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="columns">
        <div class="column">
            <h1 id="h1" class="title has-padding-top-15" style="text-align: center;">
                {{ $product->name }}
            </h1>
        </div>
    </div>

    <div class="columns has-margin-top-50 is-centered">
        <div class="column is-6">
            <div class="card">
                <header class="card-header">
                    <p class="card-header-title">
                        {{ $product->name }}
                    </p>
                </header>
                <div class="card-content">
                    <div class="content">
                        Prijs: &euro; {{ $product->price }}
                    </div>
                </div>
                <footer class="card-footer">
                    <input type="submit" value="Bestel" class="card-footer-item button is-primary">
                </footer>
            </div>
        </div>
    </div>
@endsection